[package]
name = "rusty-dedup"
version = "1.0.0"
authors = ["Salvador Perez Martin <sisekeom@protonmail.com>"]
edition = "2018"

[dependencies]
radix_trie = "0.1"
serde_json = "1.0"
log = "0.4"
clap = "~2.32"
simple_logger = "~1.0"
